version: '3.8'

services:
  unvecal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unvecal-server
    ports:
      - "8080:8080"
    volumes:
      - ./tmp_input:/app/tmp_input
      - ./tmp_output:/app/tmp_output
      - ./output:/app/output
      - ./mp4:/app/mp4
    environment:
      - GOOS=linux
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
